DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
id INT AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR(250) NOT NULL,
last_name VARCHAR(250) NOT NULL,
cnp VARCHAR(13) NOT NULL,
email VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS VACCINES;

CREATE TABLE VACCINES (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(250) NOT NULL,
doses INT NOT NULL
);

DROP TABLE IF EXISTS VACCINATION_EVENTS;

CREATE TABLE VACCINATION_EVENTS (
id INT AUTO_INCREMENT PRIMARY KEY,
user_id INT NOT NULL,
vaccine_id INT NOT NULL,
dose_number INT NOT NULL,
date DATE NOT NULL
);

DROP TABLE IF EXISTS RECOVERY_EVENTS;

CREATE TABLE RECOVERY_EVENTS (
id INT AUTO_INCREMENT PRIMARY KEY,
user_id INT NOT NULL,
date DATE NOT NULL
);

DROP TABLE IF EXISTS TEST_EVENTS;

CREATE TABLE TEST_EVENTS (
id INT AUTO_INCREMENT PRIMARY KEY,
user_id INT NOT NULL,
result VARCHAR(50) NOT NULL,
date DATE NOT NULL
);

DROP TABLE IF EXISTS GREEN_CERTIFICATE;

CREATE TABLE GREEN_CERTIFICATES (
id INT AUTO_INCREMENT PRIMARY KEY,
certificate_id VARCHAR(250) NOT NULL,
user_id INT NOT NULL,
vaccination_id INT,
recovery_id INT,
test_id INT,
start_date DATE NOT NULL,
end_date DATE NOT NULL
);

